### ISSUE TITLE
Use YAML formatter

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1301]
### What should be done?

We already have formatters for the Go source and Markdown files. Let's add another one for all YAML files.

Preferably, it should support our existing style as closely as possible. Preferably, it should be written in Go; a Node.js tool inside a Docker container is the second best option.

### Where?

https://github.com/FerretDB/FerretDB/blob/main/Taskfile.yml

**Comment by chinmaym07** [comment]
HI @AlekSi I want to try this issue.
Can you give me headstart for this issue ?

**Comment by AlekSi** [comment]
[Contributing guidelines](https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md) should be a good start.

We probably should hook into that target: https://github.com/FerretDB/FerretDB/blob/cdb6c36cb67406f361eb94f53d892f660742f76c/Taskfile.yml#L122-L126 Or make a new one

**Comment by wqhhust** [comment]
I'd like to have a try, using go yaml package.  Just Unmarshal and then Marshal it.
[sample](https://go.dev/play/p/4Z7hdVj200Z)

**Comment by AlekSi** [comment]
Let's try that, but I'm not sure if go-yaml/yaml#709 would be a problem for us or not.

**Comment by wqhhust** [comment]
@AlekSi yaml in golang doesn't work well for this task: the Marshall method will output with indent of 2 which is not configurable,  while the majority of yml files in the project has indent of 4. I created an issue [able to configure indent](https://github.com/go-yaml/yaml/issues/957), but it might took a long time for it to ready.

javascript lib js-yaml is much more mature, so maybe currently we could use docker to run node

**Comment by AlekSi** [comment]
@wqhhust We would be fine with changing indentation for all YAML files to 2. Preserving comments formatting and positioning is more important.

**Comment by wqhhust** [comment]
@AlekSi After marshel the yml files using golang, I found 3 things it changed:
1:  merged multiple lines into one line
![image](https://user-images.githubusercontent.com/5955201/233096819-0b8991bf-0ff1-450c-883b-c2fedb18c97d.png)
2: removed the beginning line in a file which is "---"
![image](https://user-images.githubusercontent.com/5955201/233098393-f5688f06-f76c-4434-8d41-f3e7941e76cc.png)
3: Reformat comment in the same line by remove some space, this is good.
![image](https://user-images.githubusercontent.com/5955201/233099572-f56ef6a1-aafd-4981-8027-478a2272db52.png)

For comments formatting, it changed the position which is not good, but one workaround is: instead of put the comment in a separate line, we could just put it on the same line. Like the following, but we need to manually change such comment to the same line
![image](https://user-images.githubusercontent.com/5955201/233100249-d218912a-377d-4260-af8b-ac7ea3976398.png)

**Comment by AlekSi** [comment]
Uh, yeah, does not look very good. Let's try some nodejs-based formatter.

**Comment by wqhhust** [comment]
@AlekSi prettier works very well for this case. Please help review PR https://github.com/FerretDB/FerretDB/pull/2485
After I run the command "task fmt-yaml", the git status is
![image](https://user-images.githubusercontent.com/5955201/233234239-f89f77c6-71f2-4f00-93ad-975e8621b7ba.png)
