### ISSUE TITLE
Remove `types.Incomparable`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#1522]
Currently, `types.Compare` could return four results: less, greater, equal, and "incomparable". The latter is used in two cases: when comparing NaNs, and when comparing documents. Both those cases should no longer exist after #1151 and #1521. Let's remove `types.Incomparable`.

Split `types.Compare` into that function and `types.CompareOrder`.

Later: Come up with better names? Think about future changes.

**Comment by chilagrow** [comment]
To remove incomparable, we need to a way to find if two values are same type or not. The user case is for $gt, $gte, $lt or $lte. For example if we compare `{"foo" {$lt: 5}}` on value {"foo": "bar"}, it should be false because string and number cannot be compared. 

At the moment, it is handled by returning `types.Incomparable` to indicate 5 and "bar" cannot be compared.

How about exposing `Comparable(a, b any) bool` from types package which allows us to check if two values can be compared, then we perform comparison. Suggestion welcome.

**Comment by AlekSi** [comment]
> if we compare {"foo": {$lt: 5}} on value {"foo": "bar"}

We never compare (using `types.Compare`) those two values. In this example, `types.Compare` is called with `(5, "bar")`.

> string and number cannot be compared

Any two values can be compared. In this case, 5 < "bar" due to types order: https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/

**Comment by chilagrow** [comment]
So this one is about filtering and not about comparison. If I understand correctly, we must filter so we never call `(5, "bar")` for this specific example.

**Comment by AlekSi** [comment]
> So this one is about filtering and not about comparison

This issue is about removing `types.Incomparable`. That value is returned only by `types.Compare`. This issue is mostly about the comparison.

> If I understand correctly, we must filter so we never call (5, "bar") for this specific example.

No. Let's say we run `find` command with `filter` argument being equal to `{"foo": {$lt: 5}}`. We fetch documents and call `common.FilterDocument(doc, filter)`. That function should return true if `doc` matches `filter`, and false otherwise. It eventually calls `types.Compare(doc.Get("foo"), 5)` and compares the result with `types.Less`:
```go
if types.Compare(doc.Get("foo"), 5) == types.Less {
  return true
}
```
`doc.Get("foo")` might return a "bar" string, so we do call `types.Compare("bar", 5)`.
