### ISSUE TITLE
Test with CockroachDB

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#1523]
Blocked by a part of #3662.

We should add CockroachDB into our local testing setup: Docker Compose configuration, Taskfile.yml, envtool changes, etc.
It would be better if we could do that without full duplication, but that's optional. We definitely should not add a new backend in this issue, though.

Some tests will most likely fail. That's expected in this issue.

We should add ["Go Extra"](https://github.com/FerretDB/FerretDB/blob/main/.github/workflows/go-extra.yml) CI configuration for FerretDB+CockroachDB.

**Comment by tracker1** [comment]
Saw the application on HN today, and my first thought was this could be pretty cool on top of CockroachDB, which I know has a more limited surface than PostgreSQL proper, but would really appreciate this.

**Comment by ptrfarkas** [comment]
@tracker1 Thanks for reaching out!

Have you seen the articles of Artem Ervits at CockroachDB? I linked them below. 

He experimented with FerretDB+CockroachDB and wrote a series of articles on it.  We haven't tested it ourselves, so we don't support it officially. Please test it, and let us know how it went.

Also, these are older articles, so the feature set has improved since.  

https://dzone.com/articles/migrating-mongodb-collections-to-cockroachdb-with
https://dzone.com/articles/using-cockroachdb-as-a-backend-for-oss-mongodb-alt
https://dzone.com/articles/experimenting-with-unique-constraints-in-cockroach
https://dzone.com/articles/cockroachdb-multiregion-abstractions-for-mongodb-d

**Comment by gedw99** [comment]
I really like CockroachDB compared to postresql.

**Comment by gedw99** [comment]
@ptrfarkas did you find any code samples from those links ? would like to test.

**Comment by dbist** [comment]
hi @gedw99, I don't have any code samples as I was just improvising. What specifically do you need? Here's my docker compose repo https://github.com/dbist/cockroach-docker/tree/main/cockroach-ferretdb. You can run CDC with CockroachDB core but its limited compared to the enterprise version. Frankly, I've never tried it. You can run `cockroach demo` which gives you a fully capable enterprise version for an hour or use CockroachDB Serverless, which has a generous free tier and CDC is included.

**Comment by dbist** [comment]
Also, here are the gists with the code used in the articles:

https://gist.github.com/dbist/df732ae51cb290db08bbabaf506ca154
https://gist.github.com/dbist/c94fa979663b27ab35e896fd455024c7
https://gist.github.com/dbist/31ccdf25ee33644ffb66e7ef3540549c
https://gist.github.com/dbist/935194a62edcef8fd24822c7eeb6f1f0
