### ISSUE TITLE
Tigris `$set` updates Datetime and ObjectID value to string field type should throw validation error

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#1830]
### Versions

0.8.1

### What did you do?

Added compat test cases for `$set`.
Using `$set` operator  `DateTime` and `ObjectID` are set to `string` field type in Tigris. The field type stays as string but value stored is DateTime` and `ObjectID`.

See the issue number in the code base.

### What did you expect to see?

Same as compat.

### What did you see instead?

In `TestUpdateFieldCompatSet` testcase `ObjectID`, the field type string is set with objectID value.
```
        	            	--- expected
        	            	+++ actual
        	            	@@ -6,5 +6,3 @@
        	            	   "_id": "string",
        	            	-  "v": {
        	            	-    "$o": "000102030405060708091011"
        	            	-  }
        	            	+  "v": "AAECAwQFBgcICRAR"
        	            	 }
```

### Environment

```markdown
- OS:
- Architecture:
- Version:
- Go:
- Git:
- Deployment:
- Deployment details:
```

**Comment by rumyantseva** [comment]
This issue is similar to https://github.com/FerretDB/FerretDB/issues/1835, should be covered by https://github.com/FerretDB/FerretDB/issues/1061.

Let's not close the issue because the issue number is mentioned in the source code, but it should stick together with https://github.com/FerretDB/FerretDB/issues/1061
