### ISSUE TITLE
Research if we could support the RocksDB storage engine

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2498]
### What should be done?

There is a really cool project called [Odysee](https://odysee.com/), it's a decentralized streaming platform that offers less regulated content. I believe it to be a competitor to YouTube. It's built on top of [LBRY](https://lbry.tech/spec?_ga=2.91710812.778274981.1682068080-1320596755.1679256508), a peer-to-peer protocol that uses blockchain technology.

LBRY uses RocksDB and MongoDB as described [here](https://github.com/lbryio/rocksdb/blob/8d664ccb071f2b6844a765835f14c19336426121/docs/_posts/2015-07-15-rocksdb-2015-h2-roadmap.markdown?plain=1#L33), which they call [MongoRocks](https://github.com/mongodb-partners/mongo-rocks).

It would be cool if we could offer RocksDB as a backend. 

We should try to fully understand the performance characteristics of RocksDB and why they chose to use it. 

* https://discord.com/invite/SJMUq8EjXB

**Comment by adetunjii** [comment]
@b1ron  I don't think FerretDB can support RocksDB storage engine. Primarily because FerretDB isn't built using storage engines but existing database systems which in turn use their storage engines. This deviates from FerretDB's original objective. It would be way too much work and a whole lot of refactoring would need to be done to support data access through storage engines directly. 

Moreover, RocksDB is written in C++, so there's currently no feasible way to cross-compile C++ code directly to go.
