### ISSUE TITLE
Find a better tool for CHANGELOG.md generation

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2682]
### What should be done?

Currently, we use GitHub's built-in changelog generator: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

We want to replace it with something that could be run locally to simplify our release process.

One good feature of the current tool is that it uses PR titles, not commits. The new tool should have that feature too.

Another feature we want to have is some customization with templates.

---

Once the tool is found, we should add it as a dependency (via tools.go or as a Docker image) and make it available via `task changelog`.

### Where?

Takfile.yml

### Definition of Done

- `task changelog` works.
- changelog is regerated for the previous releases.

**Comment by wazir-ahmed** [comment]
@AlekSi There is a [REST API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release) to generate the release note content (markdown) without actually creating a release in GitHub. Since we already expect the developer to configure `GITHUB_TOKEN` in their dev env, I think we can `curl` this API and get the notes.

**Comment by AlekSi** [comment]
I think I would still prefer some other existing tool with customization

**Comment by vigneshsankariyer1234567890** [comment]
Hey, if this is still a pending issue, I would love to try it out!

**Comment by vigneshsankariyer1234567890** [comment]
@AlekSi I found this tool called [git-chglog](https://github.com/git-chglog/git-chglog), which is written in Golang. We have an option of either running it as a Docker container, or using it as a direct dependency.

Once a template and workflow is defined, running this is simply:

```bash
git-chglog -o CHANGELOG.md
```

By integrating this into the `Taskfile.yml`, we can generate the Changelog appropriately for the latest version. Would this be a sufficient solution?

**Comment by AlekSi** [comment]
> One good feature of the current tool is that it uses PR titles, not commits. The new tool should have that feature too.

It does not look like git-chglog uses PRs.

**Comment by vigneshsankariyer1234567890** [comment]
It does use PR Titles out of the box, and is currently what they use themselves when generating their changelog between versions:

<img width="773" alt="image" src="https://github.com/FerretDB/FerretDB/assets/68676914/3137d157-c970-443a-b856-02bca138e673">

It's also possible to maintain the same style as the current Changelog.

**Comment by vigneshsankariyer1234567890** [comment]
@AlekSi Understood what you meant by that.

Can I clarify that in essence we need some tool that does the following:

1. Get the list of PRs merged since last version. This can be done using a simple API call, as mentioned by @wazir-ahmed
2. Get the list of labels from PRs
3. Group PRs by labels that we want to use in the PR, which would be provided in some sort of config file
4. Render new version (as provided by some template) and merge existing CHANGELOG with new version CHANGELOG

Unfortunately, there are not many out of the box solutions sufficiently allow this type of workflow, since the idea of Pull Requests are mainly relevant to only GitHub. However, majority of the solutions focus on commits specifically since it is an intrinsic part of Git itself, shared across Git-based version control platforms.

I tried the workflow above for steps 1 and 2 which are fairly easy. The latest tag and date of tag can be obtained with a git command, which can be executed using [Google's GitHub wrapper](https://github.com/google/go-github) or with the [go-git](https://github.com/go-git/go-git). Subsequently, using a variant of the cURL command

```bash
curl -H "Accept: application/vnd.github+json" \
"https://api.github.com/search/issues?q=repo:FerretDB/FerretDB+is:pr+is:merged+merged:>=2023-08-28"
```
we can get all PRs. The great thing is the PR response from the Git endpoint has both the title of the PR and the label.

<img width="544" alt="image" src="https://github.com/FerretDB/FerretDB/assets/68676914/f7612d58-da4f-4347-b4c3-2bb816d8f527">

Subsequently, some data processing can be done to filter and group the PRs by some input labels, and finally render the new version and merge the existing CHANGELOG based on the template.

Of course, this isn't very trivial to do, but I believe that this could yield good results.

**Comment by AlekSi** [comment]
Merging with existing CHANGELOG (and some minor tweaks) could be done manually. The new version's changelog could be rendered to the stdout.

We would much prefer not to maintain one more tool ourselves. We might make our own, but only if no one exists already.

**Comment by vigneshsankariyer1234567890** [comment]
Got it. That would be doable as well!
