### ISSUE TITLE
Implement `envtool version` command

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2684]
### What should be done?

We should implement a new `envtool` command that is very similar to `shell read` subcommand, but reads a fixed file build/version/version.txt and omits the leading `v` in the output. It should exit with non-zero exit code on any error.

See #2685 for the reason why we need that command.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/cmd/envtool

### Definition of Done

`go run ./cmd/envtool version` produces something like `1.2.0-1-g6170f970a`.

**Comment by jeremyphua** [comment]
Hello! Can I work on this? Thanks in advance!

**Comment by jeremyphua** [comment]
Hey @rumyantseva , just to double check. The fixed file to read should be `build/version/version.txt` instead of `build/version/commit.txt` right?

**Comment by rumyantseva** [comment]
Hey @jeremyphua, thanks for asking!

Yes, you are absolutely right, the file should be `build/version/version.txt`.

And yes, it would be great to add tests! Since the file `build/version/version.txt` is regenerated every time we build FerretDB, I'd say it should be safe to just rewrite it at the beginning of the test. So, a test could be similar to some other tests in `envtool_test.go` where we generate files with known content before dealing with them. Or alternatively, the filename can be set as a param of the function that reads the file, and then it's possible to generate some other files and use them for testing.
