### ISSUE TITLE
Support `$bit` bitwise update operator

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#821]
### What should be done?

https://www.mongodb.com/docs/manual/reference/operator/update/bit/

### Where?

In the common handler code.

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated:
- - dot notation;
- - all data types;
- - overflows and underflows;
- spot refactorings done;
- user documentation updated.

**Comment by dcoppa** [comment]
Hi!
We are developing a product based on Open5Gs.
We would like to use FerretDB rather than MongoDB, also for consolidation purposes since we're already using PostgreSQL for other functions of the product (less moving parts the better).
Unfortunately this is not possible at the moment, because Open5Gs is using the $bit operator.
Do you have an estimation of when this issue will be closed?
Thank you

**Comment by adetunjii** [comment]
@rumyantseva I would like to take up this issue

**Comment by AlekSi** [comment]
@adetunjii any news? Anything we could help you with?

**Comment by adetunjii** [comment]
I've made head way. I'll raise a PR soon

**Comment by dcoppa** [comment]
Just a quick update:
I have compiled FerretDB with the patch from https://github.com/adetunjii/FerretDB/commit/729b63d1b7e668dabdcbb50b1742c9a00983a9d5 and now I have a working Open5Gs setup using FerretDB instead of MongoDB.
UEs can access the 5G network and everything seems to work fine.
Thanks a lot! Cannot wait for this to land into the main branch ;)
